version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/image-train-filters-fe"
    schedule:
      interval: "daily"
    groups:
      angular:
        patterns:
          - "@angular*"
          - "angular*"

  - package-ecosystem: "npm"
    directory: "/e2e"
    schedule:
      interval: "daily"
