version: "3.7"
services:
  itf-fe:
    hostname: frontend
    build:
      context: ./docker-files/.
    volumes:
      - ${PWD}/image-train-filters-fe/dist:/usr/share/nginx/html
    expose:
      - 8080
    networks:
      - itf

  itf-backend:
    hostname: backend
    build:
      context: ./service/.
    expose:
      - 5000
      - 5000/tcp
    networks:
      - itf

networks:
  itf:
