name: PR image-train-filters-web

on:
  create:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - 'README.md'
      - 'Readme.md'
  push:
    branches:
      - '**'
      - '!master'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'adopt'
    - uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install SBT
      run: sudo apt install curl; \
            export SBT_VERSION=$(curl -s https://api.github.com/repos/sbt/sbt/releases/latest | grep "tag_name" | awk '{print $2}' | tr -d '",' | sed 's/^v//'); \
            curl -L https://github.com/sbt/sbt/releases/download/v$SBT_VERSION/sbt-$SBT_VERSION.tgz | tar xz; \
            sudo mv sbt/bin/* /usr/local/bin/

    - name: Install Jest Image Train Filters Web
      run: cd image-train-filters-fe && yarn && yarn add jest --dev

    - name: Run Tests and Build
      run: make build
