name: PR image-train-filters-web

on:
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - 'Readme.md'
  push:
    branches:
      - '!master'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install Jest Image Train Filters Web
      run: cd image-train-filters-fe && yarn && yarn add jest --dev

    - name: Run tests
      run: sbt test

    - name: Run Build
      run: make build
