name: PR image-train-filters-web

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install Jest Image Train Filters Web
      run: cd image-train-filters-fe && yarn && yarn add jest --dev

    - name: Run tests
      run: sbt test

    - name: Run Build
      run: make build
