name: Update sbt dependencies

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Scala
        uses: actions/setup-scala@v12
        with:
          java-version: 'adopt@1.11'
          scala-version: '2.13.6'

      - name: Run sbt updates
        run: sbt dependencyUpdates

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update sbt dependencies
          branch: update-sbt-dependencies
          title: 'Update sbt dependencies'
          body: |
            This pull request updates the following dependencies:
            - Dependency updates

          labels: dependencies
